### ISSUE TITLE
Homepage : list of links

### ISSUE THREAD

**Issue by nyl-auster** [contentacms/contenta_vue_nuxt#15]
<img width="1421" alt="capture d ecran 2017-10-20 a 12 11 10" src="https://user-images.githubusercontent.com/335495/31815962-9f6d5dcc-b58e-11e7-86d4-55dc1b74d81d.png">
Create links to the "all recipes" page, to get them filtered as explained here :  http://contentacms.readthedocs.io/en/latest/demos-consumers-implementation-guidelines/#front-page

1. Create a new "all recipes" page  ( look this page as an example https://github.com/contentacms/contenta_vue_nuxt/blob/master/pages/recipes-latest/index.vue )
So you need to create a "pages/all-recipes/index.vue" file and a PageRecipesAll component
2. This page can get params from url to filter the recipes
3. link from the homepage are just passing get params in url to filter this page.

**Comment by jeanfei** [comment]
Ok for the task, I'm working on it.

**Comment by jeanfei** [comment]
Yann, voila la PR à reviewer : https://github.com/contentacms/contenta_vue_nuxt/pull/25

**Comment by jeanfei** [comment]
On peut l'a clôturer ou mettre l'issue en done :)
