### ISSUE TITLE
Implement "features" listing page

### ISSUE THREAD

**Issue by nyl-auster** [contentacms/contenta_vue_nuxt#18]
@see http://contentacms.readthedocs.io/en/latest/demos-consumers-implementation-guidelines/#features-listing-page

Ensure with @e0ipso that corresponding content types and content exists in public API ?

https://www.drupal.org/files/issues/Umami%20-%20Features%20-%20v1%20-%20Desktop.jpg

**Comment by e0ipso** [comment]
Thanks @nyl-auster I will give this some thought. At the moment we don't have a good solution for this, since it's a bit layout-y.

**Comment by nyl-auster** [comment]
okay, i remove it from the sprint to v1 until we know how to do :)
