### ISSUE TITLE
Implement "Get in touch" contact page

### ISSUE THREAD

**Issue by nyl-auster** [contentacms/contenta_vue_nuxt#19]
http://contentacms.readthedocs.io/en/latest/demos-consumers-implementation-guidelines/#get-in-touch-page-contact-page

I did this : https://contentavuenuxt.github.io/contact/
But this does not send any http request to post a mail, because at the time i did this, Drupal contact form had a bug and it was not possible to post a mail with an http request.

We should solve this issue, maybe with a another drupal module if needed, a rule, something ? Contact form is a very common features and should possible to implement with decoupled D8

Contact link should be added in the footer

**Comment by jeanfei** [comment]
Du coup, en attente de ce point la : https://www.drupal.org/node/2843755
