### ISSUE TITLE
Rewrite in a clean way DrupalJSONAPIQueryString.js

### ISSUE THREAD

**Issue by nyl-auster** [contentacms/contenta_vue_nuxt#2]
add some recursivity + enhance units tests with a more complex query

https://github.com/contentacms/contenta_vue_nuxt_pwa/blob/master/services/DrupalJSONAPIQueryString.js

**Comment by dawehner** [comment]
Is this something which could be published as a npm package? This could be useful for other implementations as well, I assume?

**Comment by nyl-auster** [comment]
@dawehner well i guess there is already an existing package that does that, i have to check :-p

It not, it may be useful for others JS clents and published it as package would be the way

**Comment by dawehner** [comment]
At least in my elm implementation I certainly will write a similar library
as well. It is certainly helpful to have a more descriptive way of saying
what you want than "JUST" a query string.

**Comment by nyl-auster** [comment]
Maybe i miss it but did not found a existing npm package that do this : https://www.npmjs.com/browse/keyword/jsonapi

**Comment by nyl-auster** [comment]
Rewritten with a fully recursive function

**Comment by e0ipso** [comment]
Recursion rulez!

**Comment by nyl-auster** [comment]
Now a npm package : https://www.npmjs.com/package/d8-jsonapi-querystring

**Comment by e0ipso** [comment]
👏 will you ping the other consumer devs in Slack to let them know about
it?
