### ISSUE TITLE
[CRITICAL BUG] Recipes pages broken 

### ISSUE THREAD

**Issue by nyl-auster** [contentacms/contenta_vue_nuxt#23]
Click on homepage, then click on any recipes on the homepage : that gives us a 404.

**Comment by nyl-auster** [comment]
links are broken (wrong uuids) when dev console is off, but correct when dev console is on, with chrome

**Comment by jeanfei** [comment]
I think the problem from the broken links comes from that the demo site in https://contentavuenuxt.github.io/ which is generated in static (see index.html contains ids) with old ids from https://dev-contentacms.pantheonsite.io/api. 
I think that *contentacms pantheon was re-installed*, which has generate new uuids which cause broken links. 
So if you go directly, to https://contentavuenuxt.github.io or https://contentavuenuxt.github.io/recipes/ , static version is returned with old ids (with broken links). 
But if you go to the homepage, go to recipes menu item, the data are fetched from pantheon, and the ids are ok. 
To solve this, I think you just need to rebuild static version of contentavuenuxt.github.io with new ids. but the problem will arrived again if contentacms api is re-installed.

**Comment by jeanfei** [comment]
J'ai fait la PR sur l'autre dépôt https://github.com/contentavuenuxt/contentavuenuxt.github.io/pull/1

**Comment by nyl-auster** [comment]
fixed
