### ISSUE TITLE
npm install failed

### ISSUE THREAD

**Issue by geraldvillorente** [contentacms/contenta_vue_nuxt#24]
```
$ npm install
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.1.2
npm WARN preload-webpack-plugin@1.2.3 requires a peer of webpack@^3.2.0 but none was installed.
```

My OS is `Ubuntu 16.04 64bit`.

**Comment by geraldvillorente** [comment]
So after a bit of Googling I found [this thread](https://stackoverflow.com/questions/36725181/not-compatible-with-your-operating-system-or-architecture-fsevents1-0-11) in SO. And the `fsevents` was gone but the webpack is still there.

**Comment by nyl-auster** [comment]
@geraldvillorente does it mean you can't run "npm run dev" and "npm run start" ?

**Comment by jeanfei** [comment]
For me, it works from master branch, with :
```
$ npm i 

$ npm run dev
```

on OSX with node v8.6.0 + npm 5.3.0

**Comment by geraldvillorente** [comment]
All good folks. Thank you.
