### ISSUE TITLE
Create guidelines for components organization

### ISSUE THREAD

**Issue by nyl-auster** [contentacms/contenta_vue_nuxt#3]
What happens now : 
- components pages fetch all datas 
- datas flows down from pages components to components children
- components children may events up if needed
- a store may be added if it is required by components communcation but "pure" components and internal state is preferred when possible.
- components should have a corresponding unit test

**Determines what will be the components from the wireframes and out to organize components directory**

**Comment by dawehner** [comment]
I really like initiatives like this as it helps people to find best practices!  It's the stuff people have a hard time during day to day work. In case you have some good recommendations it might be though also worth writing a blog post about it

**Comment by nyl-auster** [comment]
See https://github.com/contentacms/contenta_vue_nuxt/wiki
