### ISSUE TITLE
Would love to maintain this project

### ISSUE THREAD

**Issue by victorkane** [contentacms/contenta_vue_nuxt#40]
Hi there,

I've been working with Nuxt.js and with Vue.js for about a year now, and before that with React. As [victorkane](https://www.drupal.org/u/victorkane) I've been part of the Drupal community for [over a decade](http://awebfactory.com/node/96).

And at [DurableDrupal](https://github.com/DurableDrupal) we're inventing the wheel! And writing a book about migration from Drupal to Full Stack.

Wanna go with Contenta and, especially, ContentaJS, and put my shoulder to the wheel for there to be SSR based on Nuxt. The possibilities are numerous.

How can we get started?

**Comment by nyl-auster** [comment]
@victorkane i sent you an invite link for this repo. Feel free to ask for any questions if needing. Not working anymore on it but Drupal headless + Nuxt si for sure a interesting combination, it deserves some love.

**Comment by victorkane** [comment]
Great!

**Comment by alexfinnarn** [comment]
Have you thought more about what you want to do with this project @victorkane? 

I'm at a DrupalCamp right now, and I'm starting to build an application that needs an API but I don't think needs a CMS. Someone pointed me to this project, and lo and behold I made the last few PRs, lol. Don't remember doing that...

Anywhoo, I'm interested in seeing what you are planning to do, since last time I checked in with this project, it was also looking for a maintainer.

**Comment by victorkane** [comment]
Hello @alexfinnarn, yes, my plan is as follows:

* [now] getting up to speed with ContentaCMS
* make a new branch using current stable nuxt + vuetify releases (to start in about two weeks) using standard build processes
* update to Nuxt 2 when that is released as stable and not just in nuxt-edge
* make a branch using the new ContentaJS
* make a branch using alternative simple Node.js/Express/MongoDB proxies

**Comment by nyl-auster** [comment]
@victorkane what is the point of ContentaJS ? I did not understand the use-case : why Drupal would need a Node JS middleware additionally to the API ?

**Comment by victorkane** [comment]
Please check out the README of ContentaJS: https://github.com/contentacms/contentajs 

Also you should follow many of the decoupled real-world experience over the past few years. For truly "de-coupled Drupal" the objective should be:

* for Drupal to do what it does best: manage content, decoupling itself not only from the frontend but also from the actual mass serving of content (road taken by Lullabot since 2015 for example).
* for a proxy server (Node.js (contentajs is one example), go, etc.) to do what it does best: scale with performance for high-traffic or complex sites in the actual serving up of mass structured content.
* for front end apps of alls kinds (in this example Vue.js/Nuxt.js) to do what they do best, consuming structured content

**Comment by nyl-auster** [comment]
@victorkane I checked it out but the benefits and what it does exactly did not seem obvious to me.  For example : 
- With cache on JSON API ressources / responses, Drupal can scale without a NodeJS server.
- Proxies to get meteo data in a non-block way from client or creating a micro services can be coded in PHP
- A middleware with anti-fraud service before accessing the content can be coded on PHP side and has to be synchronous ( first check, then serve content)

Was just wondering if adding by default a NodeJS proxy is not adding extra-complicity that fits only for big use-cases. 

I see the big picture though : using Contenta CMS only as a content service like contentful, and use Node.js for custom code and microservices. 

For my curiosity : How contentaJS is playing with Nuxt node server ?

**Comment by victorkane** [comment]
@nyl-auster ok, you may be right, but a lot of people don't agree with you. If you are satisfied with Drupal/LAMP as structured content server without performant proxy for your use cases, my advice is to go with it, sure! It isn't that one way is better than the other, it's a question of what you need.

In any case, my roadmap here in this module is purely from the point of view of a NuxtJS frontend consuming ContentaCMS itself, first and foremost.

In terms of your last question, as some social networks say, it's complicated. The role of Node.js within Nuxt is not to act as a structured content server (i.e. to accept requests for data and return json) but rather to take on the responsibility of transforming what would be a simple single page app into a Universal app, with server side UI rendering of the HTML, to make the frontend app more SEO compliant. See first paragraphs of the [Nuxt guide](https://nuxtjs.org/guide).

ContentaJS, on the other hand, is a proxy with the responsability for serving up structured content directly to the frontend.

Anyhows, our first steps will be for this Nuxt.js example to run well with ContentCMS itself (consuming its API), as well as to provide guidelines for creating your own versions as per your own content strategy and content model.

**Comment by nyl-auster** [comment]
@victorkane thanks for explaining your point of view. I won't say i'm satisfied with LAMP but i would rather go to Strapi than Drupal if NodeJS is added as a full part of the equation. Glad you have plans for the next steps !

**Comment by victorkane** [comment]
@nyl-auster sure! Strapi is wonderful, wonderful, especially if you are starting from scratch. In fact, one way I've used is to create a Strapi API, then use drush scripts to upsert content there, and add in then any front end you like directly to strapi. Done that and happy to help anyone who needs help doing those drush scripts.

But, the question is, given the tens of thousands of Drupal sites (especially Drupal 7's and 6's and even some 5's still out there, but also an increasing number of D8 sites), how do I get my Drupal content to full stack JavaScript or other modern architectural stacks??? I've worked for a decade building Drupal sites for clients and mentoring teams. I feel a great responsibility to help all of us move on to what's actually going on now in the industry.

I think Contenta may be just the ticket for that, and it makes for a great CMS.

As I said before, there's no right way and wrong way, it's a question of your use cases.

**Comment by nyl-auster** [comment]
Ok !  I'm glad you have strong opinions about what this project should become, looking forward to see your work :)

**Comment by victorkane** [comment]
@nyl-auster 👍🏼

**Comment by nyl-auster** [comment]
So, for now i came back a little bit on this project, because I spent a lot of time on it the last year. I strongly want this to remain exactly what it is from the start : something as simple as possible to get the very beginners started with SSR / JSON API. So no contentajs for this repo, and PR should remove code rather than add some code. 

I think a contentajs + nuxt is an excellent idea that should go to another repo, so that people more advanced can have more advanced use cases , and we can very easily share things between the two repo

**Comment by Yusadolat** [comment]
Hello,
I'd love help maintain this project. I'm currently working on headless Drupal with NuxtJS for my company

**Comment by yann-yinn** [comment]
Hello. Sorry for the delay,  was in vacation. Are you still interested ?

**Comment by victorkane** [comment]
> @victorkane So, for now i came back a little bit on this project, because I spent a lot of time on it the last year. I strongly want this to remain exactly what it is from the start : something as simple as possible to get the very beginners started with SSR / JSON API / Vue.js. So no contentajs for this repo, and PR should remove code rather than add some code.
> 
> I think a contentajs + nuxt is an excellent idea that should go to another repo, so that people more advanced can have more advanced use cases , and we can very easily share things between the two repo

1. Never got any kind of support from Contenta chat apps in terms of "simple as possible to get the very beginners started", since it's essential to know how to get Contenta up and running easily for starters. No docs on how to easily get Contenta running.
2. contentajs + nuxt is the purported objective on THIS repo, why should there be another one?
3. Since last year have moved on to other solutions for my Drupal clients trying to rescue their stuff, replacing Vue with React + Hooks + Context, and replacing ContentaJS with other easier to work with solutions.

Thanks.

**Comment by yann-yinn** [comment]
Hello ! i was speaking to @Yusadolat but thanks for your feedback

1) **my** objective was to make headless Drupal easier with this repo, so this sounded reasonable that next maintainer have a similar vision, for the followers of this repo. 

2) I never intended to support contentajs, which i respectfully disagree with, and it did not even existed when I started this repo. Having a Node.js middleware + a PHP server + a complex front-end with SSR is over-engineering for me, SSR is already hard by its own, and so Drupal 8 is ...

3) yep react Hooks are awesome (Vue 3 will have the same system). What are you using instead of Contenta today ? 

thanks to Contenta experience and other decoupled stuff, I moved to easier solutions and i am working i a start-up on our own headless solution now :) If interested in a headless blogging engine, check it here : https://www.mypod.cloud/, will be released in september. That is only dedicated to blogging though, not a full headless CMS like Drupal, GraphCMS and such.

**Comment by victorkane** [comment]
@yann-yinn Thanks so much for your comments and for sharing what you are working on now. I will do the same shortly! Very interested in GatsbyJS, on the one hand, and for CMS, either Drupal itself, or else Wordpress or BackDrop (the latter 2 easier, but whatever monolith the legacy site is built on (there are GatsbyJS plugins for most!)); or... react-admin https://github.com/marmelab/react-admin (really worth looking into if you have a decoupled Node.js/MongoDB or whatever back end server with REST API or GraphQL, which it is capable of recognizing and setting up interactive CRUD forms, etc., and is fully programmable. I prefer it to https://strapi.io/, which is cool, but much too sui generis and oft-changing for my liking.

Be back in a few weeks with some concrete examples, videos, etc!

**Comment by yann-yinn** [comment]
Cool, thanks for your valuable feedback. Yep JAMstack stuff like Gatsby / Gridsome. Pod is designed from the ground to work with a JAMstack architecture, i think this is an awesome way to get a superfast and powerful blog. I do work with custom Node.js / Mongodb , so I will make sur to take a look at react admin :)

**Comment by Yusadolat** [comment]
@yann-yinn 
Yes, I'm pretty much Interested
