### ISSUE TITLE
Fresh install gives this error

### ISSUE THREAD

**Issue by ludo1960** [contentacms/contenta_vue_nuxt#55]
Even tried:

const serverBaseUrl = 'https://live-contentacms.pantheonsite.io';

![image](https://user-images.githubusercontent.com/41955921/57587802-1d64ae80-7503-11e9-8e70-96b089bb2857.png)

**Comment by ludo1960** [comment]
Anabody there?

**Comment by erdemalkan** [comment]
@ludo1960 #57

**Comment by ludo1960** [comment]
@erdemalkan Thanks a lot, got it working!

**Comment by Yusadolat** [comment]
@ludo1960 Glad, you got it working.
Can you share what went wrong and fix Apply for any other person having this issue.

**Comment by ludo1960** [comment]
Hi, I just used VS Code to change all instances of  files: 'filename,url', to  files: 'filename,uri',
in the the lib/api.js and it worked.
